version: 2

sources:
 - name: basket_craft
   database: basket_craft
   schema: raw
   tables:
     - name: products
       columns:
         - name: product_id
           description: Primary key for products
           tests:
             - unique
             - not_null
         - name: created_at
         - name: description
         - name: product_name
     - name: orders
       columns:
         - name: order_id
           description: Primary key for orders
           tests:
             - unique
             - not_null
         - name: created_at
         - name: website_session_id
         - name: user_id
         - name: primary_product_id
         - name: items_purchased
         - name: price_usd
         - name: cogs_usd